Stop("Casa da Ribeira - Igreja", Location(0.0, 0.0))
Stop("Largo S. Bento", Location(0.0, 0.0))
Stop("Ponta Negra", Location(0.0, 0.0))
Stop("Hospital", Location(0.0, 0.0))
Stop("Jardim Duque da Terceira", Location(0.0, 0.0))
Stop("Bairro - Império", Location(0.0, 0.0))
Stop("Quinta da Vargem", Location(0.0, 0.0))
Stop("Canada do Célis", Location(0.0, 0.0))
Stop("Ribeirinha (Serra)", Location(0.0, 0.0))
Stop("Largo do Terreiro", Location(0.0, 0.0))
Stop("Praça Velha - Sub-Urbanas", Location(0.0, 0.0))
Stop("Ribeira do Testo", Location(0.0, 0.0))
Stop("Serretinha", Location(0.0, 0.0))
Stop("Cabo da Praia", Location(0.0, 0.0))
Stop("Regatos", Location(0.0, 0.0))
Stop("Fontinha", Location(0.0, 0.0))
Stop("Boa Hora", Location(0.0, 0.0))
Stop("Praça de Toiros", Location(0.0, 0.0))
Stop("Refugo", Location(0.0, 0.0))
Stop("Praça Almeida Garrett", Location(0.0, 0.0))
Stop("Fonte da Faneca", Location(0.0, 0.0))
Stop("Salto", Location(0.0, 0.0))
Stop("Atalaia", Location(0.0, 0.0))
Stop("Av. Álvaro Martins Homem", Location(0.0, 0.0))
Stop("Cinco Ribeiras", Location(0.0, 0.0))
Stop("Canada da Fontaínha", Location(0.0, 0.0))
Stop("Alto das Covas - Escola", Location(0.0, 0.0))
Stop("Raminho", Location(0.0, 0.0))
Stop("Fanal", Location(0.0, 0.0))
Stop("Serreta (Estalagem)", Location(0.0, 0.0))
Stop("Praça Velha - Urbanas", Location(0.0, 0.0))
Stop("Cruz das Cinco", Location(0.0, 0.0))
Stop("São Bartolomeu (Igreja)", Location(0.0, 0.0))
Stop("Biscoitos", Location(0.0, 0.0))
Stop("Posto 1", Location(0.0, 0.0))
Stop("Ribeirinha - Caminho Novo", Location(0.0, 0.0))
Stop("Vila Nova - Praça", Location(0.0, 0.0))
Stop("Biscoitos - Caparica", Location(0.0, 0.0))
Stop("Lajes - Igreja", Location(0.0, 0.0))
Stop("Fonte Bastardo - Império", Location(0.0, 0.0))
Stop("Álamos Bravos", Location(0.0, 0.0))
Stop("Cruz Dourada", Location(0.0, 0.0))
Stop("Grota do Medo", Location(0.0, 0.0))
Stop("Guarita", Location(0.0, 0.0))
Stop("Base Aérea 4", Location(0.0, 0.0))
Stop("Portões de S. Pedro", Location(0.0, 0.0))
Stop("Quinta da Pata", Location(0.0, 0.0))
Stop("S. João Deus - Largo", Location(0.0, 0.0))
Stop("Ribeira dos Pães", Location(0.0, 0.0))
Stop("Reguinho", Location(0.0, 0.0))
Stop("Grota do Vale", Location(0.0, 0.0))
Stop("Quatro Canadas", Location(0.0, 0.0))
Stop("Ribeirinha", Location(0.0, 0.0))
Stop("Quatro Ribeiras - Igreja", Location(0.0, 0.0))
Stop("Cerrado do bailão - Fim", Location(0.0, 0.0))
Stop("Altares - Igreja", Location(0.0, 0.0))
Stop("Zona Industrial", Location(0.0, 0.0))
Stop("Carreirinha", Location(0.0, 0.0))
Stop("R. Dr. Henrique Bráz", Location(0.0, 0.0))
Stop("Praça Almeida Garrett - Tribunal", Location(0.0, 0.0))
Stop("Lar de Idosos", Location(0.0, 0.0))
Stop("Estrela", Location(0.0, 0.0))
Stop("Canada Nova de Sta. Luzia", Location(0.0, 0.0))
Stop("Alto das Covas", Location(0.0, 0.0))
Stop("Terreiro", Location(0.0, 0.0))
Stop("Azória", Location(0.0, 0.0))
Stop("Doze Ribeiras", Location(0.0, 0.0))
Stop("Posto Santo - Igreja", Location(0.0, 0.0))
Stop("Ladeira Grande - Império", Location(0.0, 0.0))
Stop("Bairro - Forte", Location(0.0, 0.0))
Stop("Praça de Toiros - Estacionamento", Location(0.0, 0.0))
Stop("Biscoitos - Igreja Velha", Location(0.0, 0.0))
Stop("Canada de Belém", Location(0.0, 0.0))
Stop("Canada das Covas (Chafariz) 2", Location(0.0, 0.0))
Stop("Pesqueiro", Location(0.0, 0.0))
Stop("Pico Gordo - Entroncamento", Location(0.0, 0.0))
Stop("Canada das Covas (Chafariz)", Location(0.0, 0.0))
Stop("Pico Redondo", Location(0.0, 0.0))
Stop("Porto Martins - Igreja", Location(0.0, 0.0))
Stop("Serreta", Location(0.0, 0.0))
Stop("Canada Capitão Mor", Location(0.0, 0.0))
Stop("2 Caminhos", Location(0.0, 0.0))
Stop("Porto das Pipas", Location(0.0, 0.0))
Stop("Ribeira Seca", Location(0.0, 0.0))
Stop("Cabo da Praia - Igreja", Location(0.0, 0.0))
Stop("Fontinhas", Location(0.0, 0.0))
Stop("Tomás de Borba", Location(0.0, 0.0))
Stop("Praça Velha - Inter-Urbanas", Location(0.0, 0.0))
Stop("Bairro do Lameirinho (Entrada)", Location(0.0, 0.0))
Stop("Cruz das CInco", Location(0.0, 0.0))
Stop("Agualva - Igreja", Location(0.0, 0.0))
Stop("Praça da Vila de São Sebastião", Location(0.0, 0.0))
Stop("Vinha Brava", Location(0.0, 0.0))
Stop("Bairro Novo", Location(0.0, 0.0))
Stop("Silveira", Location(0.0, 0.0))
Stop("Terra Alta", Location(0.0, 0.0))
Stop("Santo Amaro", Location(0.0, 0.0))
Stop("Mata - Veredas", Location(0.0, 0.0))
Stop("Serra Santiago", Location(0.0, 0.0))
Stop("Pico Bagacina", Location(0.0, 0.0))
Stop("Pico Celeiro", Location(0.0, 0.0))
Stop("Rua do Ramo Grande", Location(0.0, 0.0))
Stop("São Bartolomeu - Igreja", Location(0.0, 0.0))
Stop("Largo da Silveira", Location(0.0, 0.0))
Stop("Rosário", Location(0.0, 0.0))
Stop("Lourais", Location(0.0, 0.0))
Stop("Cerrado do bailão", Location(0.0, 0.0))
Stop("Praia da Vitória", Location(0.0, 0.0))
Stop("Silveira 2", Location(0.0, 0.0))
Stop("Cnd. Cinco Reis", Location(0.0, 0.0))
Stop("Aeroporto", Location(0.0, 0.0))
Stop("Escola Tomás de Borba", Location(0.0, 0.0))
Stop("Terra Chã - Igreja", Location(0.0, 0.0))
Stop("Rua dos Fundões", Location(0.0, 0.0))
Stop("Santa Bárbara", Location(0.0, 0.0))
Stop("Praça Velha - Interparques", Location(0.0, 0.0))
Stop("S. Bartolomeu (Igreja) 2", Location(0.0, 0.0))
Stop("Largo da Cruz", Location(0.0, 0.0))
Stop("Feteira - Igreja", Location(0.0, 0.0))
